### ISSUE TITLE
Slight improvements

### ISSUE THREAD

**Issue by chriscolden** [kevinblumenfeld/PSCloudConnect#1]
Hi,

Great work on this module. Love it.

Few issues i've had to work around.

1. Connecting to Skype Online when your autodiscover points to onprem. It won't connect. Fixed by changing line 137. $sfboSession = New-CsOnlineSession -ErrorAction Stop -Credential $Credential -OverrideAdminDomain "$Tenant.onmicrosoft.com"
and line 150. $sfboSession = New-CsOnlineSession -UserName $Credential.UserName -OverrideAdminDomain "$Tenant.onmicrosoft.com" -ErrorAction Stop

2. It would be great if it modified the window title so you know which tenant you are connected too. As a consultant I'm always connecting to different tenants. Something on the lines of the below would be good.

$host.ui.RawUI.WindowTitle = "Office 365 Tenant: $Tenant"

Many Thanks for your efforts, certainly a go to module install for me.

Regards,
Chris

**Comment by kevinblumenfeld** [comment]
@chriscolden thank you for your kind words.  I have pushed the hybrid Skype code change and will update PS Gallery shortly.  However, first I would like to add the $host.ui.RawUI.WindowTitle = "Office 365 Tenant: $Tenant" that you recommended.  Can you tell me where you would see that being added?
Thanks again!
Kevin

**Comment by chriscolden** [comment]
I've added it to the Begin section.

```
Begin {
        if ($Tenant -match 'onmicrosoft') {
            $Tenant = $Tenant.Split(".")[0]
        }
        if (! $User) {
            $User = "Default"
        }
		
		$host.ui.RawUI.WindowTitle = "Office 365 Tenant: $Tenant"
    }
```

**Comment by kevinblumenfeld** [comment]
Closing (years later :-) ).  Thank you @chriscolden .  I now have Connect-Cloud and Connect-CloudMFA in Posh365.  Please let me know what you think.
